### ISSUE TITLE
Dragging clone widget drops original down in the grid.

### ISSUE THREAD

**Issue by Almightyzhir** [gridstack/gridstack.js#1117]
## Subject of the issue
I am having an issue using the helper: 'clone' feature in the draggable options. When i drag and drop a widget into another grid, the original widget will drop into the next row and go in-front of the widget below it. I would ideally like the original widget to stay in the same place so i can drag and drop it into another grid as many times as i like.

I'm fairly new to GridStack so i may just be missing out something simple to solve this.

## Your environment
* 0.6.0
* 79.0.3945.130

## Steps to reproduce
Codepen link here: [Codepen](https://codepen.io/almightyzhir/pen/oNgagXW)
Forgive the css styling

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

**Comment by adumesny** [comment]
couple issues with you code.
1) you have 2 grids, so `var grid = $('.grid-stack').data('gridstack');` is incorrect
2) in your includes you don't need jquery UI (you already include all.js) and knockout?
3) I don't beleive `data-gs-current-height` should be set. the lib sets it automatically based on content (not sure why it's not internal)
4) bad idea to have `position:absolute` on the grid items. let the toolkit position the items otherwise all bets are off

looks like you are trying to have locked items in a grid drag and get copied into another regular grid ? sounds to me like you should be using a 'toolbar' from which items can get dragged into 1 grid instead of using two. We provide couple example of that in https://gridstackjs.com/demo/advance.html and others.

**Comment by Almightyzhir** [comment]
Thank you for the tips, that was quite helpful. I've decided to opt for a toolbar instead of a second grid.
