### ISSUE TITLE
RemoveWidget() doesn't also trigger change events when it should

### ISSUE THREAD

**Issue by ronvanpol** [gridstack/gridstack.js#1142]
The function RemoveWidget should trigger change events in case that other nodes are changed. For example take the simple case where one has a simple grid containing to adjacing nodes 1 and 2. When node 1 is removed by using the RemoveWidget function, node 2 moves to the place of node 1. This is a change for node 2 and as such it should trigger the change event.

I see in the code that the triggering of this change event is commented out in several places. Why was the decision made not to trigger the change event anymore and for what reason?

**Comment by adumesny** [comment]
@ronvanpol do you have an example where the change event doesn't get called when it should ?

I commented some of the change events code because it was calling it when adding/removing a node that had NO OTHER changes to siblings, so only when x,y,w,h is changed should it now trigger (still does call it more often than absolutely necessary but tons better than before, especially when loading 5 widgets we used to get called 5 times with an ever increasing number).

if you run https://gridstackjs.com/demo/two.html and open the console you will see that removing a node in the float=false that causes re=ordering WILL call remove+change, in the float, just remove.

Please re-open if you can provide a test. use the default template. thank you!

**Comment by ronvanpol** [comment]
This bug seems to be related to nested grids. I have prepared a jsfiddle. Click on nested items "1" or "2" and the log will only show the removed events and no change events.

[https://jsfiddle.net/a7bo92vn/](https://jsfiddle.net/a7bo92vn/)

**Comment by adumesny** [comment]
thanks, I can see the issue now. will take a look...

**Comment by adumesny** [comment]
turns our you don't need nested grid, this simpler example shows the issue as well
https://jsfiddle.net/adumesny/znqx4dmr/

**Comment by adumesny** [comment]
fix in next release 0.6.4
