### ISSUE TITLE
How to save and load gridstack items ?

### ISSUE THREAD

**Issue by iCantSeeSharp** [gridstack/gridstack.js#1206]
Hi there, 

Is there a way to save and load the position of grid-stack-item? 
I can't find anything working with the last version : 1.1.0

**Comment by adumesny** [comment]
sure can, see https://gridstackjs.com/demo/serialization.html

**Comment by iCantSeeSharp** [comment]
So i have followed the demo that you linked. It works great thank you but i don't know why i can't resize the "new" fidget that have been saved. It looks like i forgot something on the saved html...

I've done this fiddle to demonstrate what it looks like : https://jsfiddle.net/fuavcbe8/

**Comment by adumesny** [comment]
sorry don't have time to debug your code right now, but for one thing you shouldn't have `ui-draggable ui-resizable ui-resizable-autohide` as those are automatically added (and drag&drop events) when adding the new widgets.
Also `addWidget()` you can just pass in the x,y,w,h directly rather than create attributes!

the demo works so see where you different and break.
