### ISSUE TITLE
addWidget works great, makeWidget generates ‘undefined’

### ISSUE THREAD

**Issue by petebytes** [gridstack/gridstack.js#1221]
## Subject of the issue
addWidget works great, makeWidget generates ‘undefined’
Am I misusing makeWidget? Thanks

## Your environment
* gridstack.js 1.1.0
* Chrome Version 83.0.4086.0 (Official Build) canary (64-bit)

## Steps to reproduce
Codepen https://codepen.io/petebytes/pen/YzXLPNZ?editors=1010

## Expected behaviour
Should work the same as addWidget and not generate undefined.

## Actual behaviour
using makeWidget generates undefined

**Comment by adumesny** [comment]
so many issues with your code...
1. you're missing a "grid-stack-item" parent div above your content
```html
<div class="grid-stack">
    <div id="gsi-1" class="grid-stack-item-content" data-gs-x="0" data-gs-y="0" data-gs-width="3" data-gs-height="2" data-gs-auto-position="true">Widget</div>
  </div>
```
2. you have 2 grids in there, yet call `GridStack.init()` instead of 'initAll()' = you will have 2 grids back,

3. when you init (the first grid) it WILL convert the item id gsi-1 (if properly parented) so why call `makeWidget()` ? the doc should explain what method is for.

**Comment by petebytes** [comment]
Sorry about that - tried to duplicate the prod environment too early in the morning :(
Thanks for taking the time for the response.
