### ISSUE TITLE
[Violation] Forced reflow while executing JavaScript

### ISSUE THREAD

**Issue by songthamtung** [gridstack/gridstack.js#1266]
## Subject of the issue
Yesterday dragging the widgets was smooth, but today it's laggy? I opened the browser console and saw it flooded with 

> [Violation] Forced reflow while executing JavaScript.

I thought it could have just been on my app, but I can also see the same warning in the advance demo page.

<img width="1280" alt="Screen Shot 2020-04-24 at 10 57 27 PM" src="https://user-images.githubusercontent.com/43738871/80232835-bdb5d380-867f-11ea-8b54-7e82b89002aa.png">

- This console warning does not appear when running locally

## Your environment
* Gridstack 1.1.1
* Chrome Version 81.0.4044.113 (Official Build) (64-bit)

## Steps to reproduce
* Go to [https://gridstackjs.com/demo/advance.html](https://gridstackjs.com/demo/advance.html)
* Open Browser Console
* Drag any widgets

## Expected behaviour
Smooth UX when dragging widgets

## Actual behaviour
Laggy and Choppy UX when dragging widgets

**Comment by adumesny** [comment]
can't reproduce using chrome (on windows, not mac) so hard to fix. 
you mentioned that it doesn't reproduce locally - you mean running out of the git tree rather than published file ? should be exact same code (minus a few unpublished fixes).

possible an extension you have is causing this - I would disable all and test.
https://stackoverflow.com/questions/41218507/violation-long-running-javascript-task-took-xx-ms

**Comment by songthamtung** [comment]
Thanks. Found the culprit.

> Grammarly for Chrome

 Disabling this extension fixed the warning messages and ux is back to being seamless.
