### ISSUE TITLE
$el.draggable is not a function in v2

### ISSUE THREAD

**Issue by ritox842** [gridstack/gridstack.js#1390]
## Subject of the issue
After upgrading to version 2.0 I'm getting `$el.draggable is not a function` for all of my widgets 
![image](https://user-images.githubusercontent.com/7280441/94169510-91ed8280-fe97-11ea-8f27-a19b1724c61e.png)

I saw some similar issue https://github.com/gridstack/gridstack.js/issues/1363
I wasn't able to reproduce it in jsFiddle. Tried to import jquery and jqyertUI and its working so I don't really knows why in my app Im getting this error. For my understanding its an issue with how gridstack grabbing jquery-ui.

While debugging I found that in [this file] (https://github.com/gridstack/gridstack.js/blob/5c421b796faa3d01646bf835b2da3cdd87de6193/src/jq/gridstack-dd-jqueryui.ts) we're taking the element any parsing it with $() that cause it to e an array and therefore draggable is not a function
![image](https://user-images.githubusercontent.com/7280441/94538081-3c74f500-024c-11eb-9a6b-cd8039444aeb.png)

Tried to pass a regular element and an element as a string and getting the same issue

## Your environment
* gridstack 2.0
* all browsers

## Expected behaviour
Widgets should be draggable.

## Actual behaviour
Getting error that gridstack's addWidget doesn't recognised $.draggable

**Comment by adumesny** [comment]
why did you create another bug instead of just updating #1374 ?
the element you are passing isn't the issue, looks like a jquery-ui init problem. How are you including gridstack and are you bringing any lib that might be bringing jquery or jquery-ui as well that might conflixt and override our jquery-ui version ?

|  with $() that cause it to e an array and therefore draggable is not a function
no, that just converts to a jquery object to call JQ UI methods like .draggable

**Comment by adumesny** [comment]
please re-open with new info
