### ISSUE TITLE
Gridstack not respecting gs-y attribute on initialising

### ISSUE THREAD

**Issue by Rainbowlemon** [gridstack/gridstack.js#1535]
## Subject of the issue
Items in pre-existing HTML are being ordered incorrectly with respect to their `gs-y` attributes once GridStack.init() is called.

## Your environment
V3.1.2, using HTML5
Chrome 87.0.4280.88

## Steps to reproduce
https://jsfiddle.net/Rainbowlemon/721ce803/44/
Sometimes the order is correct if you reorder the HTML, but sometimes it isn't.

## Expected behavior
Items should be ordered according to their gs-y attribute

## Actual behavior
Items are being ordered semi-randomly and item order is being influenced by its position in the DOM on gridstack init

**Comment by adumesny** [comment]
you need to have grid `float: true,` for the items to stick to their Y values and not gravitate to the top, then you can set it to false...

but I guess `init()` should do that for you since you are not explicitly calling `addWidget()` one at a time. actually bacthMode should prevent in between layout until we're done loading...

I can take a look.

**Comment by adumesny** [comment]
fixed in next release! make sure to donate if you find this lib useful.
