### ISSUE TITLE
Dragging will endlessly scroll/too fast.

### ISSUE THREAD

**Issue by bcbuddy** [gridstack/gridstack.js#1576]
## Subject of the issue
First and most critical for me, you can drag an item infinitely down the page. 

Secondly, it seems that with the new HTML5 DD update, the "scroll" property in dragInOptions is always set as "true" and we have no control over it.

Finally, the speed in which an item drags is incredibly fast. It would be nice to have some control over it.

Issues 1 & 3 combined can be very annoying together.

## Your environment
3.1.4 with HTML5 DD

## Steps to reproduce
Use your advance demo: https://gridstackjs.com/demo/web2.html
Grab an item in the grid, drag it to the bottom of the page.
Note how fast it moves and that it will drag forever. This is a real pain when a user needs to drag something around at the bottom of a grid container.

## Expected behavior
Most importantly, I would like the infinite dragging fixed. An item should not be dragged past the bottom of the page(or it's container if specified? I know you guys noted that containment is not supported yet with HTML5 - hopefully soon!). 
I would like the option to enable/disable scrolling.
I would also like the option to increase/decrease sensitivity of the drag

## Actual behavior
Items can be dragged forever down the page.

**Comment by adumesny** [comment]
dragging/resizing past the bottom is by design (see #1001) but I agree that it is way too fast... not sure we need option to turn it off if designed correctly (flag seems like a band-aid to me).

looking at code commend (which I have not verified) rhlin says:
```js
  scroll?: boolean; // nature support by HTML5 drag drop, can't be switch to off actually
```
but I'm having so many html draggable issues (on mac, safari) that I started implementing plain mousedown/mousemove instead, in which case we could possibly support whatever options we want.

but this is a all a ton of work, so help or donation would be appreciated.

**Comment by adumesny** [comment]
well don't worry, in v6 it apparently doesn't scroll at all :) - see #2032
