### ISSUE TITLE
height too small with `cellHeight:auto` loading in 1 column

### ISSUE THREAD

**Issue by ayman-metwally-developer** [gridstack/gridstack.js#1600]
## Subject of the issue
Nodes heights shrink in one-coloumn-mode.

## Your environment
* Version 3.2.0 
* Browser: 88.0.4324.104 (64bit)

## Steps to reproduce
1. Simply use the jsfiddle example and set disableOneColumnMode to false.
2. Decrease the width of the browser to the minimal possible width.
3. Click "Run" and observe the height of the nodes.
https://jsfiddle.net/aymanmetwallybu/af5vy16w/3/

Also, the example on the home page has this issue. (See screenshots below)
jsfiddle sample:
![image](https://user-images.githubusercontent.com/24887181/106302517-bf8d7280-6261-11eb-9e93-c1b3520f0afa.png)

Homepage demo:
![image](https://user-images.githubusercontent.com/24887181/106302379-910f9780-6261-11eb-9e26-54d4c0612ca0.png)

## Expected behavior
Nodes should maintain their heights in OneColumnMode (i.e. Node height should be the same in both modes).

## Actual behavior
Nodes heights shrink. This issue was not present in earlier versions (for example 1.1.0).

**Comment by adumesny** [comment]
yeah, there is an easy workaround to set `cellHeight:100` or something then it's the same 12 or 1 column mode. The problem is I changed the default to 'auto' (was 70px) because it's now smart enough to make square cells by default, BUT it calculates things in default 12 column mode, but when you load into <768px wide grid we switch to 1 column mode and you probably don't what 700px tall cells either, but 700/12 is also kinda small...

not sure what the **right** behavior is, other than maybe have a minimum height if we load into 1 column directly and cellHeight is set to auto. Either case the user has complete control of the `cellHeight` property. there just isn't a 12 column vs 1 column cellHeight option (not sure there should be either).

Comments ?
@aryatekpia had the same issue in #1413

**Comment by kevinlandsberg** [comment]
Thank you @adumesny !!!

**Comment by kevinlandsberg** [comment]
When will you deploy new version?

**Comment by adumesny** [comment]
couple more fixes before I do... likely this wkd.

**Comment by kevinlandsberg** [comment]
Thanks man!
