### ISSUE TITLE
Dynamically Added DND Items not picked up GridStack Init

### ISSUE THREAD

**Issue by harisenbon** [gridstack/gridstack.js#1637]
## Subject of the issue

I have a Widget "drawer" that isn't loaded when the Grid is initialized, but is loaded afterwards.

Because it's loaded after the initial event, the elements don't get the `dragStart` event attached that they need to be droppable on the grid.

So, when I call `GridStack.init({dragIn: '.widget-template'})` the Grid is there, but the widgets aren't.

Then when I open the "drawer" I need to re-initialize the dragIn on those elements.

Created from Slack Discussion:
https://gridstackjs.slack.com/archives/C0LPPLXJR/p1614264670015600

## Your environment
* gridstack 3.3.0 using html5
* vue 2 (Although this same issue exists in plain HTML)

## Steps to reproduce
Code:
```
GridStack.init({dragIn: '.widget-template'})
```

After Grid initialization, add `<div class="widget-template">Drag Me</div>` to the DOM

## Expected behavior
The "Drag Me" element should be draggable

## Actual behavior
It is not draggable or droppable.

## Hacky Solution
I found a reference to `grid._setupDragIn();` and run it when I open the drawer to re-connect those items, but it feels incredibly hacky, and I was wondering if there was a specific way to initialize the setupDragIn on dynamically added elements.

## Proposed Solution
(From Alain)
> I can make the method public and able to call multiple times (will skip items already done). 

Best,
Keith

**Comment by adumesny** [comment]
will be in next 4.x release. was more work than I expected (I made the API static as it's not really tied to a grid instance, while preserving old behavior)

if you find lib useful, don't forget to contribute!

**Comment by jedwards1211** [comment]
@adumesny I'm still having this issue if my `GridStack.setupDragIn()` call happens after my `GridStack.init()` call.  The element becomes draggable but the grid doesn't respond to it.

Looking through the code, I see the problem is that the dragIn selector is executed at the time that `GridStackDDNative.droppable` is called (via `GridStack.init`) and options/listeners specific to that grid are passed directly to the draggable element.

We should refactor so that grids and external drag in elements are completely uncoupled and all interaction happens through the DD manager as an intermediary.

* `setupDragIn()` runs the selector immediately and register the matching elements with the DD manager
* Only DD manager installs event listeners on the draggable elements
* Grid only registers listeners on the DD manager
* When an element is dragged, the DD manager's listener decides which Grid(s)' listeners to call

With this architecture, draggable elements would be registered with the DD manager as soon as `setupDragIn` is called, and even if a Grid is created later, it will be able to get drag events for those elements from the DD manager.

**Comment by jedwards1211** [comment]
Actually maybe I misinterpreted how some things work.

My confusion came from

```
  public droppable(el: GridItemHTMLElement, ...)
```

Even though `_setupAcceptWidget` is calling `droppable` on the grid's root element, rather than an item element.

It seems like the architecture does decouple the draggable elements and grids like I was suggesting, yet I still have the initialization order problem for some reason.

**Comment by jedwards1211** [comment]
Okay sorry, I was confused, the problem was that I was trying to dynamically change `opts.acceptWidgets`.

Are options not dynamically changeable if there's not a documented method to change them?

**Comment by adumesny** [comment]
glad it all worked out. don't forget to donate if you find the lib useful.
