### ISSUE TITLE
JQ: Drag and drop from top to bottom

### ISSUE THREAD

**Issue by pawel-k-kazmierczak** [gridstack/gridstack.js#1737]
## Drag and drop from top to bottom
It's not possible to drop widgtet to the bottom when between is other widget.
part of #1094 

## Your environment
* 4.2.1 jQuery commit: 860b844e15291d3f4a423a7677ee5174b91dbee6 
* Chrome 89.0.4389.128

## Steps to reproduce

https://jsfiddle.net/qfLk581w/1/

Or localy: 
let items = [
      {x: 0, y: 0, w: 6, h: 3},
	  {x: 6, y: 0, w: 6, h: 3},
      {x: 0, y: 3, w: 8, h: 2},
	  {x: 0, y: 5, w: 4, h: 2}
    ];

## Issue
It's not possible drop '0' below '3' at once. To do this user must put '0' between '2' and '3' first.

https://user-images.githubusercontent.com/13885829/115266617-a695ae80-a138-11eb-8950-99c1606ef432.mp4

For HTML5 it works fine.

**Comment by adumesny** [comment]
surprised jq and h5 would behave differently as the collision is shared between the two. I am not seeing what you are seeing (Chrome Win10) as it will add new rows for me and let me insert below... humm.

I do see a flicker as it decides where to put the item between 2 possible spots though, so some work remain, but otherwise it adding where expected. Did you have float:false in your video ? the only thing I can think of...

here is a simpler version https://jsfiddle.net/adumesny/rfLg39ec/ (h5 and jq behave the same)

https://user-images.githubusercontent.com/3496166/115577332-317dc280-a279-11eb-9a3d-deca6cfc3e7a.mp4

**Comment by pawel-k-kazmierczak** [comment]
Hi,

I tried your link. For h5 works, for jq doesn't:
https://jsfiddle.net/p54wcz97/

https://user-images.githubusercontent.com/13885829/116079425-11df0380-a698-11eb-874d-01c4a24a0b18.mp4

thanks!

**Comment by adumesny** [comment]
you're right. JQ (which has not been my focus) has the extra issue at the bottom... https://jsfiddle.net/adumesny/rfLg39ec/

I would appreciate donations for this as I've spent way to much time on v4, and these are hard to debug and fix...

**Comment by adumesny** [comment]
no longer having jq in v6. closing
