### ISSUE TITLE
Fast dragging Issue 

### ISSUE THREAD

**Issue by qasimhassankhan** [gridstack/gridstack.js#1942]
## Dragging item down fast the gridstack looses the item
As you can see in video the green background behind is the gridstack main container and an item inside it , if i try to place the item at the bottom of the screen the gridstack looses the item while dragging. 

## My Gridstack Settings:
{
            column: 200,
            float: true,
            cellHeight:1,
            minRow:100,
            marginBottom:5,
            marginTop:5,
            marginRight:5,
            animate: false,
            marginLeft:5,
            disableOneColumnMode : true,
            acceptWidgets: true,
            resizable:{
                handles: 'e,w,se,s'
            },
}

https://user-images.githubusercontent.com/46297749/160077012-980863ca-20c7-42c4-8133-7963ed420d8a.mp4

**Comment by adumesny** [comment]
you can't have cellHeight=1 and margin=5 as that's supposed to be inclusive of top+bottom margins. Also with column=200 you better have correct CSS generated ahead of time. In your video the cell doesn't follow the cursor (seems frozen) is that video only issue or does it really not follow the cursor - I would use correct values first then open a bug if still present. if you move the mouse fast enough it WILL move the item out of the grid instead of infinitely growing the grid as designed. Also you don't have marginTop. just set margin:5 for all sides.

closing until you can show real issue.

**Comment by qasimhassankhan** [comment]
I have correct CSS generated for 200 column. 
Cell not following cursor may be the video issue, it is fine actually.
I don't want item to be removed even if i move it fast.

**Comment by adumesny** [comment]
you need to post a reproduceable example - see bug template.
