### ISSUE TITLE
multiple nested grids with regular HTML items in between

### ISSUE THREAD

**Issue by josephclawrence** [gridstack/gridstack.js#1945]
I am working on a project with a lot of tab widgets. Each parent tab widget is a GridStack item in a parent GridStack layout, capable of being moved and resized. Each tab widget has at least two tabs. 

Ideally, I would also like each tab to be a nested GridStack, capable of holding multiple GridStack items. This is currently impossible because I can have a maximum of 1 nested GridStack inside each tab widget GridStack item.

Is this something that is currently being considered, or could be considered, for further development?

Thank you.

**Comment by adumesny** [comment]
sounds like a dup of #1943 - anything can be done with the right donation. I just don't have free bandwidth these days.

**Comment by josephclawrence** [comment]
OK, thank you - how can I contact you privately? I don't think this is a duplicate, since I'm talking about multiple nested GridStacks at the same hierarchical level, not more and more deeply nested GridStacks.

**Comment by adumesny** [comment]
you mean like https://gridstackjs.com/demo/nested.html already does ? parent has 2 items that are subgrids (darker yellow). 

Not sure why you would want `subGrid` property to be an array - that woudl also break today's API and complicate the code to handle either types so not clean.  if you wanted to move a bunch of subGrids as one, then you could do that today with a parent item that has multiple subgrids items - 2 nested subgrids, hence dup of the other request ? (which I thought would work but didn't test in the demo code).

**Comment by adumesny** [comment]
draw a picture of what you are looking for...

**Comment by josephclawrence** [comment]
Sure thing - attached. I hope that helps.

One assumption I am making is that gridStack items need to be adjacent in the HTML, since that is how I have always seen it, and assume it needs to work…am I correct in that assumption?

That is why I think I need multiple nested gridStacks in order to achieve what I need.

Thanks!

Joe

Joe Lawrence

**Comment by adumesny** [comment]
I think you can do what you pictured with multiple grids, not nested in the lib way per say (since there are parent tabs in between).

the only question is what is the interaction between the dark orange items and yellow items (both grid items) ? you may or not be able to drag an orange item into the pink grid container, or you can prevent that (can only accept certain class types).

**Comment by josephclawrence** [comment]
I’m pretty sure I tried that, but when the HTML for a grid is nested inside another item, then the library automatically initialises it as a nested grid. When it then finds another one, nested inside the same parent gridStack item, it initialises that one, which overwrites the previous, since there is only space for one.

For my use case I do want to be able to freely drag between the parent and nested gridStacks, i.e. I would want to drag an orange item into the pink container.

Joe Lawrence

**Comment by adumesny** [comment]
ok, sounds like the lib would have to handle separate but nested DOM grids with regular items in between then. If want this, then you need to provide a simple example of the above html with code, and ping me directly for donation for that feature...

Otherwise you might be able to init each grid (start with children) directly with a unique id and hope it doesn't find the nested part...

**Comment by v1talii-dev** [comment]
+1, the functionality that @josephclawrence wrote about would be very useful.

**Comment by adumesny** [comment]
closing since there are no responses
