### ISSUE TITLE
Add function to remove empty grid lines [Feature-Request]

### ISSUE THREAD

**Issue by CurrentlyNoName** [gridstack/gridstack.js#1955]
Hello,

I have a grid that looks something like this:
![image](https://user-images.githubusercontent.com/51439005/164676256-41cc70da-3aa9-4d53-b474-3908313eed9f.png)

What I need it a function to optionally  remove the empty grid line (marked red in the screenshot). There is the "compact"-Function, which would remove the line, but what happens with this function is that the box with "0" would jump to the first line, which is not what i want. Is this possible or is it possible to add such a function to gridstack?

**Comment by adumesny** [comment]
`float` grids can have space by design, `float:false` will take vertical space back. If you want to move just one item (how would the lib know to move item1 but not item0 ?) then call `update()` on that item with Y:2 in the above case to move it up. You can check if there is anything taking the space using `engine.collide()`
