### ISSUE TITLE
Can't get custom draggable handle to work

### ISSUE THREAD

**Issue by idsdavidgutierrez** [gridstack/gridstack.js#2004]
## Subject of the issue
* Custom "draggable.handle" does not work with content loaded after ".addWidget()"
* It is necessary for us to load the widget content dynamically, as we do not want to save widget HTML in the database.
* The "draggable.handle" only works if the handle class is part of the HTML when we call "addWidget()"

## Your environment
* gridstack.js@5.1.1
* Edge Version 103.0.1264.71 (Official build) (64-bit)

## Steps to reproduce
1. Initialize gridstack with option to override draggable handle
2. Call .addWidget
3. Using jQuery/DOM manipulation add content to each widget that contains the draggable handle
4. Observe entire widget is draggable

https://jsfiddle.net/uxa03c82/14/

## Expected behavior
Only the content within the draggable.handle be draggable

## Actual behavior
Entire widget is draggable

**Comment by idsdavidgutierrez** [comment]
Just wanted to add another fiddle. Showing the same content added directly via "addWidget" and everything working ok.
https://jsfiddle.net/6s13zn5g/

**Comment by adumesny** [comment]
the html element drag event handlers can only be added when the widget is created, and since it's not there, it default to entire item content.... then later you add content with the handle id, but gridstack has no way of knowing (that I know) that content has changed... So you would have to tell it again to hook the drag handlers but I doubt calling `update()` with (new) handle id would make a difference as drag&drop is done at creation time today.

this would require a new feature to be able to update/change the drag handle at runtime...

**Comment by idsdavidgutierrez** [comment]
Very well. We've rearchitected our loading to no longer use .load() so we can call AddWidget with the content we need.
