### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')     at dd-gridstack.js:369:23

### ISSUE THREAD

**Issue by mengyu987** [gridstack/gridstack.js#2039]
An error is displayed after the VUE project is packaged 
Uncaught TypeError: Cannot read properties of undefined (reading 'prototype') at dd-gridstack.js:139

**Comment by adumesny** [comment]
you don't say what rev you are using, so the line number don't line up, but I assume the first one, and what you include.
```js
GridStack.prototype._setupAcceptWidget = ...
```

https://github.com/gridstack/gridstack.js#extend-library
should work. closing.

**Comment by mengyu987** [comment]
Some files cannot be found due to a bug after Vite2.0 is built，
led to Uncaught TypeError: Cannot read properties of undefined (reading 'prototype') 
thank you for your reply
拴Q

**Comment by leiyaguang** [comment]
> 

same problem

**Comment by mengyu987** [comment]
> > 
> 
> 同样的问题

你用的是vite来构建嘛，我将我的vite2升级为vite3就没问题了，我想可能是vite的问题

**Comment by leiyaguang** [comment]
> 

是用vite2构建的，我更换了导入的地址后可以了。

**Comment by mengyu987** [comment]
> 

这样也可以，不过升级下vite也可以，2的bug太多了

**Comment by adumesny** [comment]
read the doc - https://github.com/gridstack/gridstack.js#include - wrong include way (gridstack-all.js is only packaged for html include). use
```js
https://github.com/gridstack/gridstack.js#include
```

**Comment by mengyu987** [comment]
> 阅读文档 - https://github.com/gridstack/gridstack.js#include - 错误的包含方式（gridstack-all.js 仅打包用于 html 包含）。利用
> 
> ```js
> import { GridStack } from 'gridstack';
> ```
This error is generated after referencing builds like this in VitE2 at GridStack ^6.0.1.

**Comment by adumesny** [comment]
and please write content in english as I cannot translate it. You need to provide a running example showing it is a lib issue as I don't have bandwidth to debug other people issues.

**Comment by Ninita1** [comment]
I had the same problem. Locally everything works fine, but in production I had this "_**"[Potentially unhandled rejection [3] TypeError: Cannot read properties of undefined (reading 'prototype')](https://stackoverflow.com/questions/74491651/potentially-unhandled-rejection-3-typeerror-cannot-read-properties-of-undefin)**_" error.
After some investigation I found that the problem was with the gridstack dependency.
![image](https://user-images.githubusercontent.com/12759409/203505325-97e03673-0b44-4f92-953f-feb2ce1855ad.png)
I replaced import from "gridstack" to "gridstack/dist/es5/gridstack-all" and now it works fine in production.

**Comment by Pretagonist** [comment]
I have the same issue. When I use Vue 3 / Vite and build for production I get `Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')` when the app tries to set the prototype methods for gridstack. 

My guess is that something in the new method of importing fails in some way. When using the old way it worked in prod just fine. It's hard to troubleshoot since it only happens in the  minified code but it consistently fails during SetupAcceptWidget.

Using the Vite dev servers with gridstack works without issues.

**Comment by adumesny** [comment]
fixed in next release
