### ISSUE TITLE
Vue3: removeWidget not removing node !!   float+makeWidget ->Freeze !!

### ISSUE THREAD

**Issue by lorenzocostalunga** [gridstack/gridstack.js#2115]
## removeWidget and float issues
- removeWidget not removing node from engine.
- browser FREEZE with float: true and makeWidget 

## Environment
* vue + gridstack.js: last version

## Steps to reproduce

https://codesandbox.io/p/sandbox/editable-dashboard-prototype-with-vue-gridstack-and-tailwind-css-forked-y8q0d7

**Comment by adumesny** [comment]
thank you - never used codesandbox nor Vue but I can debug in vscode now to see what's happening...
this works fine in sample float.

**Comment by adumesny** [comment]
turns out hard to debug (it's an inf loop) as I see proxy for all the node items so collision is getting wrong results (checks for items being the same, but under you demo in vscode they are not).

the following **demo vue 3 demo with float=true does work fine** adding widgets, so can you create a similar one showing your issue ? I don't want to debug Vue in remote vscode session... :(
https://github.com/gridstack/gridstack.js/blob/master/demo/vue3js.html

**Comment by lorenzocostalunga** [comment]
[vue4js.zip](https://github.com/gridstack/gridstack.js/files/10286356/vue4js.zip)

Ciao,

Try this demo.

Issues:
- When a widget is deleted it is not removed from the engine nodes.
- The browser freezes when the float parameter is enabled and a new widget is added.

**Comment by adumesny** [comment]
so I don't understand what Vuejs is doing. it appears to wrap a lot of GS entities into proxies (is that for anythign attached to a DOM element ?) which causes objects to NOT be the same, even though they have the same content (id and all).

Can someone explain this, or where it is documented ?
this would require a LOT of code changing if I someone ends up cloning stucts around from me...

![image](https://user-images.githubusercontent.com/3496166/210042111-2e204b41-592b-447e-91b6-88af883297f4.png)

**Comment by adumesny** [comment]
fixed the given demo which was freezing making widgets and not removing items. PROBLEM:
let grid = ref(null);
grid.value = GridStack.init()

was causing proxy so all items were cloned and code compares node = node instead of ids...

https://github.com/gridstack/gridstack.js/blob/master/demo/vue3js_v-for.html now works
