### ISSUE TITLE
Gridstack overrides the original target element

### ISSUE THREAD

**Issue by fredericrous** [gridstack/gridstack.js#2185]
## Subject of the issue

Gridstack overrides the original target element

## Your environment
* version of gridstack.js - 7.2.2-dev
* chrome / macos 12.3

## Steps to reproduce

see function initEvent in src/utils

## Expected behavior

I want to get the original target element as well as the gridstack one

## Use case

when I drop a card on a html element external to gridstack,
I want the event dragstop to tell me the html element I dropped it to

**Comment by adumesny** [comment]
can you explain the use case and where it's different and wy it would matter ?
also have you considered touch event in your case on mobile and how that might affect it ? thanks.

**Comment by adumesny** [comment]
| a trash bin and want to drag and drop cards from gridstack to the trash in order to remove them

that exact example is supported natively in GS - see https://gridstackjs.com/demo/two.html
(see removable: '.trash' option)

are you saying the native mouseup (which becomes a dragstop) event would have the trash as the target event ?
if we wanted to know what it was dropped on, maybe we can add that field rather than pass the raw initial event as that wouldn't be the same across browsers or mobile vs desktop....

**Comment by fredericrous** [comment]
I am gonna try the removable option, thank you for pointing this out! 

I think it is convenient to have a property that gives the original event. it could be prefixed with `unsafe_originalEvent` for example.
While I agree having an event object being the same for every browser is super important, I am septic that it is a good thing to totally hide the original event. I'm just expressing a PoV, no point to argue. I might indeed not need it in the near future

I'm fine with closing the issue and pr for the moment
