### ISSUE TITLE
load() allows overlapping widgets

### ISSUE THREAD

**Issue by cca-developer** [gridstack/gridstack.js#2492]
## Widgets should not be allowed to overlap
When calling load after items have been put in place, it will allow widgets to overlap each other.

## Your environment
* gridstack 9.2.1
* Chrome/Windows

## Steps to reproduce
https://jsfiddle.net/xc7540dt/2/
This differs from the baseline fiddle only in that it calls `grid.load(items)` at the end.  But if you drag the widgets labeled 0 or 1, you can see that there is a duplicate behind them.

## Expected behavior
The expectation is that widgets should never overlap each other.

**Comment by adumesny** [comment]
an easy fix for this example is to make sure widgets have id, but when loading a new layout it shouldn't overlap anyway.

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find this lib useful!

**Comment by adumesny** [comment]
this broke in v10.3.0 as part of this change. will need to fix it again and add it to the test suite...

SHA-1: ec3c7e4e5ebc09d4124d99090e753cdb7cb9e2a8

* load() now creates in order

* changed code to create widgets in sorted order instead of reverse order (fixed collision code to handle that case to push down items during collision)
* updated two.html to force collision loading to test
