### ISSUE TITLE
Animation issue after upgraded to 9.3.0

### ISSUE THREAD

**Issue by nhannv** [gridstack/gridstack.js#2498]
## Subject of the issue
I got the drag animation issue (I'm using framer-motion) after upgraded to 9.3.0, the issue also can be reproduced in gridstack's animation example which is using AniJS

## Your environment
* version of gridstack.js - 9.3.0
* which browser/OS - MacOS

## Steps to reproduce
The issue is occurring on Gridstack's animation example: https://gridstackjs.com/demo/anijs.html

## Expected behavior
It should smoothly when drag item.

**Comment by adumesny** [comment]
@nhannv does this work in 9.2 ? if so another one for @VincentMolinie to take a look.

At this point (and drag offset not correct fix) I'm tempted to revert back mouse dragging as we're having so many problem with your new code Vincent, and the review itself took a lot of try. I don't want to test everything that can happen. **instead** you should have added scale to the existing code instead of trowing it all away...

**Comment by nhannv** [comment]
@adumesny Yes, I can confirm the version 9.2 works fine
