### ISSUE TITLE
Incorrectly placed item after repeated insertion and deletion of a column

### ISSUE THREAD

**Issue by vmerz-mgy** [gridstack/gridstack.js#2576]
## Subject of the issue
If you add and remove columns twice, an item is displayed in the wrong column

## Your environment
* Gridstack 10.0.1
* Safari Version 17.1.2 / Chrome Version 120.0.6099.71 / MacOS Monterey

## Steps to reproduce
Watching the example says more than a thousand words ;)
Click buttons as described here
https://jsfiddle.net/vmerz/fxag04cL/151/

## Expected behavior
Item 2 should stay in column 4 (zero-based)

**Comment by adumesny** [comment]
FYI, instead of `grid.getGridItems().filter(item => { const node = item.gridstackNode;` you can just use `grid.engine.nodes.forEach(n => ...`

**Comment by vmerz-mgy** [comment]
Great - thank you very much for the suggestions for improvement and the advice on filtering

**Comment by adumesny** [comment]
Updated my link: the problem has to do I believe with having that 5 column layout stored in memory and when going back using that instead of using 'none' to skip any sort of layout. 

This is likely not an easy fix (when you modify items in say 4 column, it tries to update the layout in other columns) and will require  a donation if you want me to debug this further... or work around doing a load() of pre-computed values instead.

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find this lib useful!

**Comment by vmerz-mgy** [comment]
Many thanks for the quick processing of the issue. In my next code review I will focus on an even stricter separation of concerns in my application, maybe this will be a good start for a vue-wrapper and I can contribute a small part to the project.
