### ISSUE TITLE
Responsive grids don't render items with minW correctly on resize

### ISSUE THREAD

**Issue by rory-orennia** [gridstack/gridstack.js#2676]
## Subject of the issue
If you setup responsive column breakpoints and also set the `minW` on a widget, and resize the window/grid down to something smaller than that minW, it will render incorrectly on resize and seems to just grab the `minW * currentColWidth` resulting in this:
![image](https://github.com/gridstack/gridstack.js/assets/93952948/843c0455-6cf9-4937-b7a0-2af2a4db9279)

## Your environment
* version of gridstack.js - 10.1.2
* MacOS - Firefox

## Steps to reproduce
https://jsfiddle.net/qjb3faLk/1/
- Attempt to resize 0, works fine.
- Attempt to resize 1, it expands outside the browser while resizing

## Expected behavior
The resize display should be the size of the widget, even if that widget is currently smaller than the `minW`

**Comment by rory-orennia** [comment]
Seems to be caused by this function: https://github.com/gridstack/gridstack.js/blob/9b6c68fc04bbb711eb93cdd427a334231e537353/src/dd-resizable.ts#L287

**Comment by afhammad** [comment]
+1

Was just evaluating gridstack and testing it's responsive handling and ran into this.

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find this lib useful!

**Comment by gazhay** [comment]
Anytime I specify column in init options or via javascript after load all my items widths shrink to 0. 

similarly with most other "responsive" columnOpts.

I am using bootstrap "container-fluid" on the parent of the grid-stack div, but I think something about the responsiveness is fundamentally broken.

**Comment by adumesny** [comment]
> something about the responsiveness is fundamentally broken.

@gazhay well that doesn't help without a demo showing the issue. also often people forget to include the correct CSS for none 12 column layouts (extra.css)

**Comment by gazhay** [comment]
Can't seem to find an extra.css in the npm dist 
```
dd-base-impl.d.ts    dd-droppable.js.map  dd-manager.js               dd-touch.d.ts                 gridstack-engine.js      utils.d.ts
dd-base-impl.js      dd-element.d.ts      dd-manager.js.map           dd-touch.js                   gridstack-engine.js.map  utils.js
dd-base-impl.js.map  dd-element.js        dd-resizable.d.ts           dd-touch.js.map               gridstack.js             utils.js.map
dd-draggable.d.ts    dd-element.js.map    dd-resizable-handle.d.ts    gridstack-all.js              gridstack.js.map
dd-draggable.js      dd-gridstack.d.ts    dd-resizable-handle.js      gridstack-all.js.LICENSE.txt  gridstack-poly.js
dd-draggable.js.map  dd-gridstack.js      dd-resizable-handle.js.map  gridstack-all.js.map          types.d.ts
dd-droppable.d.ts    dd-gridstack.js.map  dd-resizable.js             gridstack.d.ts                types.js
dd-droppable.js      dd-manager.d.ts      dd-resizable.js.map         gridstack-engine.d.ts         types.js.map
```
I am also aware I wasn't helpful for not posting a demo, but I literally was just putting together code from the docs and examples - nothing extra at all - pun intended. 

I'll see if I can scrape extra.css from an example or something.

**Comment by adumesny** [comment]
![image](https://github.com/user-attachments/assets/70e9aba1-91ff-4b12-a264-8210554aeec9)
from 10.3 gzip

**Comment by davideagosti-dev** [comment]
Hi @rory-orennia  I came across this while looking at how responsive dashboard layouts behave when the available space becomes smaller than a widget’s constraints.

I’m developing DnDGem, an early-alpha open-source layout library that models hard geometric constraints separately from the dimensions at which a component’s content remains useful.

Your minW + responsive breakpoint case is particularly interesting because it raises exactly the kind of question I’m working on: what should the layout do when the available space can no longer satisfy a component’s constraints?

I don’t want to assume DnDGem solves this specific GridStack behavior, but if this problem is still relevant to you, I’d be interested in understanding the behavior you actually need. If there’s a fit, I’d also be happy to work through a DnDGem integration attempt with you rather than just asking you to test the library.

https://github.com/davideagosti-dev/dndgem
