### ISSUE TITLE
MakeSubGrid example in the documentation does not work

### ISSUE THREAD

**Issue by tsugawa** [gridstack/gridstack.js#2693]
```
const grid = Gridstack.init()
grid.el.appendChild(`
<div id="gsi-1" gs-x="0" gs-y="0" gs-w="3" gs-h="2" gs-auto-position="true">
      <div class="grid-stack" id="nested-grid">
          <div id="gsi-2" gs-x="0" gs-y="0" gs-w="3" gs-h="2" gs-auto-position="true">
          </div>
      </div>
</div>`)

grid.makeSubGrid(grid.el.getElementById('nested-grid'))
```

The example uses appendChild with an html string, but the function expects a node.

**Comment by adumesny** [comment]
don't have time to debug this right now (you didn't give a running example) but makeSubGrid() likely expected an immediate child item to convert, not one nested. also you can't create nested grid from DOM (already posted bug) - `class="grid-stack" id="nested-grid"` 

DOM creation is not as strong as API, since you are suppose to JSON serialize the data anyway. DOM is old school...
