### ISSUE TITLE
'R' can rotate fixed sized or width/height items

### ISSUE THREAD

**Issue by vela666** [gridstack/gridstack.js#2694]
![image](https://github.com/gridstack/gridstack.js/assets/69613314/e4efb3e8-59b8-4eb6-a04c-ee8e12331aad)

**Comment by adumesny** [comment]
Sorry you can't right now. Use an older build.

**Comment by vela666** [comment]
> 抱歉，您现在不能。请使用较旧的版本。好奇您为什么需要关闭它...您必须拖动它才能产生任何效果。

Because the w and h of the element are fixed, but now you can switch through the "r" on the keyboard.
Will configuration items be added in the future?

**Comment by adumesny** [comment]
ok, so that's a bug I didn't think about... are you using canResize:false or setting minW=maxW=some number  I suppose I should handle both (and also when grid is full and doesn't fit. this feature is a lot harder than it appears which is what I mentioned to the user who donated for it).
no plans fto fix it right away (unless you want to donate  for it) and I wasn't planning to add flag to disable unless I hear otherwise.

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find this lib useful
