### ISSUE TITLE
content with an object

### ISSUE THREAD

**Issue by bakman2** [gridstack/gridstack.js#2809]
## Subject of the issue
I want to be able to insert an object inside `content` instead of html.

## Your environment
10.3.1
Safari / Macos

## Expected behavior
`content` is parsed as a string, making it impossible to assign an object with properties. 

I want to be able to make a fully dynamic grid, based on a single json/javascript object, without having html inside it. I think forcing content as a string actually complicates a lot of things with this project.

**Comment by adumesny** [comment]
`content` is really not used for most real applications. in V11 (see readme) there is a `renderCB` (otherwise `addRemoveCB` where you create it all) where you can create anything you want for actual content.
in my angular wrapper, I store a 'selector' which tells me what component to create and an `input` options for param. that would your oject equivalent. GS can't possibly create the DOM/object for you.

**Comment by bakman2** [comment]
@adumesny thanks, i have been staring at the API documentation for quite a bit, now you mention the readme, which does mention this and 'You will need to create content yourself (Util.createWidgetDivs() can be used to create parent divs) ' - could this be added to the API documentation then ? or am i confused ?

**Comment by adumesny** [comment]
just store your object (or whatever you need) in `GridStackWidget` and use existing `addRemoveCB` to create entire widget part, or wait for V11 to make that simpler...

Don't forget to donate if you find this lib useful.
