### ISSUE TITLE
Layout seems to be cached when resizing

### ISSUE THREAD

**Issue by FirstVertex** [gridstack/gridstack.js#2855]
## Subject of the issue
Resizing caused an invalid layout to be displayed.
Initial render is correct, but subsequent renders after resize are erroneous.
Items were specified without x/y coordinates, simply a list which Gridstack manages.
Theorize that something about items lacking x/y coordinates is befuddling the resize render.

## Your environment
* version of gridstack.js - 11.0.1
* which browser/OS - JSFiddle/Chrome/Windows

## Steps to reproduce
Go to this Fiddle:  https://jsfiddle.net/Lgjw326y
Set up baseline state: Change the size of the result viewport so that 12 columns are visible, press "Run" button (for simulated "refresh")
Slowly resize width down to reach 9 columns.  Notice the layout did not change (invalid layout expected 9 columns, rendered 12).  Press "Run" button for simulated refresh.  see a different layout now (correct layout of 9 columns)
Slowly resize down to 6 columns.  Same thing, no layout change until refresh. (invalid layout expected 6 columns rendered 9)
Same thing on 3 column breakpoint.
Now resize upwards.  Same thing.  When crossing the breakpoint, an invalid layout is displayed.  "Refresh" (press Run) and the layout is corrected on the initial render.

## Expected behavior
Expect consistent behavior between the resize and the initial render.
Expect a 9 column layout when resizing down to 9 columns (12 column layout was rendered).
Expect a 6 column layout when resizing down to 6 columns (9 column layout was rendered).
etc.

**Comment by FirstVertex** [comment]
What is represented in the Fiddle is a very simplified reproduction of this bug we see in our production app.  For reference here's how our app looks when the bug presents when resizing from 12 down to 6 column:

<img width="806" alt="image" src="https://github.com/user-attachments/assets/d2bf4030-b952-48d8-97f4-67f58c1056c0">

**Comment by FirstVertex** [comment]
i tried `columnOpts: { layout: 'compact' }` which has less problems, but still some issues when resizing upwards (for example from 3 to 6 column it gets stuck)

**Comment by adumesny** [comment]
load in 12 column - ok
![image](https://github.com/user-attachments/assets/7c324ee7-d857-4bc1-a562-3113cf66c35b)

size down to 9 column, this is actually prefect ! it scaled and moved item (default) to keep that layout. don't know what else you expect!
![image](https://github.com/user-attachments/assets/0ac5e6e2-a0b2-492b-9350-4b29c864eee3)

if you load into that 9 column of course the layout might be different as it will try to fit your pieces (which have no position, just size) to fit, so again not sure what you expect here. there is no scaling since the load() doesn't specify (not an option) you're layout is 12 column - there is no position so no way.
![image](https://github.com/user-attachments/assets/1604eef3-24b9-4ed2-935b-97d62e21929f)

not a bug. you content has NO position so there is no way to 'cache' a 12 column layout to scale down from...

**Comment by adumesny** [comment]
start at 12 column (see code modification)
![image](https://github.com/user-attachments/assets/26ab9451-7ed2-40f4-82ec-0d32d7fe1e14)
size down to 9 (default scale+move did really good job IMO)
![image](https://github.com/user-attachments/assets/3f499909-de8f-4e0f-8ba2-38da685438c8)
size down to 6
![image](https://github.com/user-attachments/assets/77f0ccd3-55ce-4fdc-9e71-da58f0883cd7)
size down to 3
![image](https://github.com/user-attachments/assets/38f7dfbd-c12c-4738-a4c8-d769988e8fac)
size down to 1 (kept 1,2,3,4 order correctly)
![image](https://github.com/user-attachments/assets/4567ea29-9d5b-4ca4-b462-42c804233b15)
then back to 12 kept same layout for every step back up
![image](https://github.com/user-attachments/assets/63ea5241-7715-42f0-b1fd-3fb456f4375e)

as I said the ONLY reason loading in 9 | 6 | 3 | 1 directly looks different is BECAUSE you don't spell out coordinates (i.e. a layout) and there is no way today to say load() 'a 12 column layout'

**Comment by adumesny** [comment]
if you want to load() and size down/up to be the same, you best bet is `layout: 'compact',` (re-position the items in mostly list order but fill any gab, similar to load() with no coordinates. BUT this does on the current layout, so it looks **incremental not** the 'original first time loaded layout which in you case happens to be number sorted to be visually what you want.

If that is what you require I would suggest doing you own loading instead (there is a column callback) for each step

'compact' initial 12 column
![image](https://github.com/user-attachments/assets/57222914-d326-4a94-83d2-f9cbc76d33bd)
down to 9 (SAME as loading)
![image](https://github.com/user-attachments/assets/91f919b1-8c61-4c41-a153-3d38a1d0ad0f)
down to 6 (SAME as loading)
![image](https://github.com/user-attachments/assets/ecc1e4c2-d544-47d5-955c-b3b03b7b7f08)
down to 3 - NOT SAME as loading (incremental from 6 column, not loading blank into 6)
![image](https://github.com/user-attachments/assets/55b8c03f-aed5-46f4-aec4-202cebcab38f)

that last step is visually more corerct when going from 6 -> 3 but doesn't match loading into 3. can't please everyone...
