### ISSUE TITLE
AutoScroll Improvement like muuri.dev 

### ISSUE THREAD

**Issue by depak379mandal** [gridstack/gridstack.js#2870]
## Need Scroll on drag improvement like https://muuri.dev
I think there are many issues related to this #2728 #2666 and many more

I just wanted to have it clean scroll on drag for every device, I also want to donate for this You are maintaining and doing great stuff with hard work. I really appreciate your work @adumesny. If you confirm, I will donate $200 right now for your time. That is how much I have. Let me know what do you think. I also think everyone should donate for this great project, whoever using this project. I am using react grid layout, but want to switch to gridstack, but need only scroll on drag to be fixed.

**Comment by adumesny** [comment]
@depak379mandal thank you for the recognition but you need to be very specific about what scrolling use case you need be looked at as there are many areas to look at - can't boil the ocean. Also you will need others to pitch in as that amount is unortunately very small given the amount of work scrolling can be.

took a quick look at muuri and not sure what scrolling you compare to.

Also curious on what react grid layout (I assume you mean react-grid-layout) not working for you. I hear people switch to gridstack from it regularly, even though we don't have a bundle react wrapper yet. working on it...

**Comment by depak379mandal** [comment]
Thanks for the reply @adumesny Let me prepare videos, It is just small fix for scrolling Smoothing and improvements,

The issue
https://drive.google.com/file/d/1Thfm95AraP2OGspL7I6Ne3OyspfOXMso/view?usp=sharing

The solution in muuri.dev
https://drive.google.com/file/d/190TgFrwBti9QJxgV3No1QyfEwK74FqV2/view?usp=sharing


Will be great to have it, So I will switch my whole project gridstack and can also contribute to amazing library.

Also donated, Thank you

**Comment by depak379mandal** [comment]
@adumesny Can you reply? Love to hear from your side.

**Comment by depak379mandal** [comment]
@adumesny 
It would be great, to have this feature. Just a small scrolling fix. You have very best knowledge of it. Just wanted to contribute to this library. Also, will be contributing, If you got some time to improve this. Please let me know.

I even never used this library but wanted to switch, It will be very motivating if you are able to resolve this issue. I really appreciate and respect your time, that is why I donated as much as I can.

**Comment by depak379mandal** [comment]
@adumesny If you don't have time and not wanted to work on this, Can you please give back the donation, I will approach to other library. Let me know.

**Comment by depak379mandal** [comment]
Hello, I implemented scroll fix in here https://www.npmjs.com/package/danimai-gridstack, Please improvise it here, if you got time. I really loved the library, but need your support. Already implemented the concept, it is working but can be improvised. And we can make gridstack js perfect.

**Comment by adumesny** [comment]
Can you please submit a code review instead for me to check and take a look ? thanks.

**Comment by lorenzogonnelli** [comment]
@adumesny, the way you are handling this issue is complitelly unacceptable to be honest. @depak379mandal donated $200 in good faith, even tried to fix the issue himself, and still, there’s been little or no effort from your side. Your attitude has been dismissive and hostile, despite the support. It's been weeks of waiting with no effort made on your end. The lack of professionalism and disregard for your community’s support is frustrating. Even donating. At this point, it’s hard to justify continuing with this library when basic issues are being ignored

**Comment by adumesny** [comment]
@lorenzogonnelli sorry you feel that way. I had personal issues this past weekend and could not work on this beloved library... I do this on my own spare time, and don't get paid for this. If you think $200 (which by the way I never asked/agreed upon, but very much appreciate) is enough for me to drop work to take a look, it maybe pays for 1h.

I only asked for those changes to be pushed in a CL so I can easily review and commit with possible fixes rather than hunt a personal branch. Not sure what's hostile about that. If you maintain a lib and have dozens of people ask for things, and do this on your own spare time, you might understand.

**Comment by lorenzogonnelli** [comment]
It's not necessarily what you asked that comes across as hostile, but how you asked it. There’s no gratitude shown for the people contributing to this project—people doing work that, in theory, should be your responsibility.

It’s also worth noting that you regularly ask for donations, even for minor fixes. This is likely why someone donated without you explicitly requesting it this time. The fix itself isn’t complicated, and you are clearly the most qualified person to address it.

I raised my issue months ago and never received any feedback beyond being told to ‘donate to get it fixed.’ Yet, even with donations, nothing seems to change. At this point, it might be fair to label this library as unmaintained.

This bug affects every Apple user, making the library unusable on Apple devices. We’re asking politely for a fix, but there seems to be little interest or initiative on your side. I know you have personal issues and other priorities to deal with, but please understand this is a serious problem, and we truly need your help. This issue is causing significant problems for us, and you’re the only one in a position to resolve it.

**Comment by adumesny** [comment]
@lorenzogonnelli #2666 must be the issue you are referring to. If you read my last comment, I said I could take a look if I could duplicate this on my machine using emulation mode (windows+chrome) and to reach out on slack to cover that work, but you never did... 

this is an open source, is free, use a lot of my spare time, and you are welcome to fix things yourself, and there is no guarantee that I would fix what is important to you. When you say `it won't let me use this library for my ios customers` clearly you are getting paid to use this and expect me to fix things for you right away and for free ? give me a break.

maintaining an open source is a thankless job and people like you make me want to drop this, or make ti licensed paid version only...

**Comment by depak379mandal** [comment]
@adumesny @lorenzogonnelli both are talking about their own intentions, But @adumesny my simple thing was if you are working on something mine I donated for that If it seems less, and you don't want to work on it, then just return the damn money. It seems like greed making you blind, I don't use this library, I wanted to be great developer to have it working as per my intention and also donated for that also worked hard on the library instead of crying about. If something seems low to like $200 it is not low for me, It is half month salary of mine. You don't respect it, But I have my own respect. You are not even discussing the issue. Just flaunting what are you doing, what you are suffering from. Don't give me that, you're just saying you earn $200/hour but even after that You don't give your insight on work and also deny returning it. I just don't use grid stack wanted to use this library, but developer like does need more king like treatment. Always remember something does not value you might value everything someone else. If you don't want to give any time or resource, I don't want that, but I want my precious time as I have given as donation $200 as it represents my hard work of half month.

In any chat I never mentioned I just need to work for me for this feature, I said if you have time please do this. You don't have time, I did it myself. But even after that you don't to give me my money, which you never respected.

Also, stop asking donation if you don't have time to work on the project. If they are giving it as they are using and donating, take it. 

The library does not support my requirements also not wanted to part of this community. Thanks Bye
