### ISSUE TITLE
Grid of previously saved items does not affect position

### ISSUE THREAD

**Issue by teq-smu** [gridstack/gridstack.js#35]
Hey,

I cannot set position of previously saved items like described in issue #13 
The size of the items are okay but not the position

Is it linked to the _styles attribute from the grid that is not been regenerated as at the time of saving.

I can give you my source files if you need to reproduce the issue ; or discuss about that

Regards,

**Comment by devSam123** [comment]
Hello! In my project we have a functionality to pin a specific grid stack item , pinning means restricting from resizing and dragging and also locking its position, so that no other item can shuffle it while it's being dragged. This has to be done at run time. I have taken reference from https://github.com/tropicalista/angular-gridstack. We have an angular app. Any help would be greatly appreciated.

**Comment by oshields** [comment]
Did you look at the locked option?  Believe that prevents other drags from moving the item around.

**Comment by devSam123** [comment]
Thanks for your response! Yes i tried manipulating the 'data-gs-locked' , 'data-gs-no-resize' and 'data-gs-no-move' options run time. By doing so i am able to lock/unlock a specific item.

I faced another issue after that, we have a functionality of adding and removing widgets run time.I tried using -  $('.grid-stack').data('gridstack').remove_widget(el,true);, but after doing so other widgets gets misaligned and they don't come back to normal mode again. Kindly help me adding and removing widget run time.
