### ISSUE TITLE
function locked doesnt lock widget

### ISSUE THREAD

**Issue by tomasjurasek** [gridstack/gridstack.js#36]
Hi,
If i use function locked, i get stack-item and want lock it, but if i lock with true i can move with this item.

 $(".grid-stack").on('dblclick', function (event, ui) {
        var grid = $('.grid-stack').data('gridstack');
        var el = event.target;
        if (el != null) {
                grid.locked(el, true);
        }
    });

**Comment by shani759** [comment]
Hi @troolee 
I have tried the code provided by @tomasjurasek  and turns out he was right. Even when i **resize** the widget over that widget (whose locked = true) that widget still leaves its place and goes below.
But if i hardcoded the **locked: true** in **gridstack.js** then it works fine.
Please look into it.....
