### ISSUE TITLE
ERROR TypeError: $(...).gridstack is not a function  

### ISSUE THREAD

**Issue by orbitboy007** [gridstack/gridstack.js#674]
I am trying to use gridstack with angular2 i am using all possible way but this error not gone. can any one help me to figure it out??

ERROR TypeError: $(...).gridstack is not a function
    at my-grid-stack.component.ts:23
    at ZoneDelegate.webpackJsonp.627.ZoneDelegate.invokeTask (zone.js:398)
    at Object.onInvokeTask (core.es5.js:4116)
    at ZoneDelegate.webpackJsonp.627.ZoneDelegate.invokeTask (zone.js:397)
    at Zone.webpackJsonp.627.Zone.runTask (zone.js:165)
    at ZoneTask.invoke (zone.js:460)
    at timer (zone.js:1540)

Index.html file contain  :
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://troolee.github.io/gridstack.js/dist/gridstack.css" />

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0/jquery-ui.min.js"></script>    
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>    
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.5.0/lodash.min.js"></script>    
<script src="https://troolee.github.io/gridstack.js/dist/gridstack.js"></script> 
<script src='https://troolee.github.io/gridstack.js/dist/gridstack.jQueryUI.js'></script>

**Comment by radiolips** [comment]
Hi, @orbitboy007 . You should use the gridstack.js and gridstack.jQueryUI.js files in CDN rather than the ones you listed. That won't fix your problem, but is still necessary.

I don't have experience with angular, but if you could provide a jsfiddle we can try to help you diagnose the issue.

**Comment by tonywr71** [comment]
I've managed to get it working with webpack and angular 2. 
To do this, in the webpack.config.vendor.js file, I put:
'gridstack/dist/gridstack.min.css',
'gridstack',
'jquery',
'jquery-ui',
'lodash',

In package.json, your lodash version will need to be "3.5.0"

In your webpack.config.js file, you need to add an alias to the jquery-ui objects that were moved into a "ui" folder. This is because jquery-ui moved the location, but gridstack didn't keep up.

My resolve statement in webpack.config.js looks like this:
```
resolve: {
            extensions: ['.ts', '.js'],
            'alias': {
                'jquery-ui': 'jquery-ui/ui'
            },
        },
```

**Comment by yangxiaolin** [comment]
import 'gridstack'
work for me! @tonywr71
