### ISSUE TITLE
Setting the `height` option to `1` breaks dragging and animations

### ISSUE THREAD

**Issue by AlexandreBonneau** [gridstack/gridstack.js#771]
Hey there, I'm trying to replicate [this behavior](https://codepen.io/AnotherLinuxUser/pen/JRvqpd) (the horizontal rearranger) with gridstack, but it seems that setting the `height` option to `1` break the ability to drag any element (except when dragging them either at the start or the end of the element list).

You can see this faulty behavior in that [codepen](https://codepen.io/AnotherLinuxUser/pen/GMKdRY).

I guess my question is, can I replicate what I want to achieve with gridstack? (cf. [link above](https://codepen.io/AnotherLinuxUser/pen/JRvqpd))

**Comment by radiolips** [comment]
@AlexandreBonneau Hey there, thanks for logging this.

There's a problem with the current dragging algorithm that prevents this sort of behavior. Unfortunately, this means you cannot currently replicate that behavior. However, it's one of the functionalities we hope to achieve in the upcoming gridstack 1.0.

I'm closing this ticket because there are a variety of open tickets that discuss this behavior, but continue checking back or checking [here](https://dylandreams.com) for more information about gridstack 1.
