### ISSUE TITLE
Positioning bug when having more than 10 items 

### ISSUE THREAD

**Issue by leowns** [gridstack/gridstack.js#793]
## Subject of the issue
When having a one column gridstack with more than 10 items the dragging or resizing of the first element causes the last item of the grid to jump to the first position. Especially when I try to resize the first element the order gets completely messed up.

## Your environment
* gridstack.js 0.3.0
* Google Chrome Version 61.0.3163.100

## Steps to reproduce
I created a JsFiddle to reproduce the issue:
https://jsfiddle.net/teq1ou97/3/

## Expected behaviour
The last element should not move.

## Actual behaviour
It jumps up to the first item in the gridstack

**Comment by DnJealt** [comment]
Can confirm. 
I've been able to reproduce this issue in our production environment with a three-column Gridstack.
It's not a big problem for us since grids like those would never occur. 
But nontheless: this is unexpected, error throwing behaviour.

![image](https://user-images.githubusercontent.com/7311113/31018547-d828549a-a52c-11e7-8f0d-371ab9e2a7d8.png)

**Comment by tonywr71** [comment]
I have an idea that @radiolips solved this in the 1.0 dev branch, as per issue #756 .

**Comment by radiolips** [comment]
Either #756 or another PR from around that time should fix it. @DnJealt or @leowns , could you try with the 1.0 dev branch?

**Comment by DnJealt** [comment]
I can't find the 1.0-dev branch anymore.. :(

**Comment by radiolips** [comment]
@DnJealt The branch is called `develop`. Hope that helps :)

**Comment by DnJealt** [comment]
Allright goodmorning everyone, hope you've had a great weekend.
I can confirm that this issue is no longer present in the v1.0.0-dev branch.

If you're still in v0.3.0 and just want this bug fixed, [you can find the fix here](https://github.com/gridstack/gridstack.js/commit/2037a70f264fd17cead83506f812ae0e025ba8c7). This is what we actually did because we were too afraid to update the rest back then.
