### ISSUE TITLE
How to resize widget to final size after animation is done

### ISSUE THREAD

**Issue by candrewtemenoscom** [gridstack/gridstack.js#829]
I should apologize. This is not an issue. I just want to see if I can some help from this forum. I would like to know how I can make the gridstack item always resize to its nearest placeholder dimension when the resize stop. I found that when it is resized very quickly, the content within the widget did not get resized correctly even though I had code to resize the content accordingly when resize stop. Later on, I find that it is because in the gsresizestop event, the widget height I got is not accurate. But if it is always resize to the placeholder size, the height is correct. Therefore, I would like to always resize the widget to its nearest placeholder when the resize stop.

* version of gridstack.js : 0.3.0
* which browser and its version: IE 11 or Chrome 63.0.3239.84

## Expected behaviour
Resize the widget to the nearest placeholder
![untitled](https://user-images.githubusercontent.com/6600394/34058000-4f45416c-e18e-11e7-92bc-5d67efc1e943.png)

**Comment by ramblingsoliloquy** [comment]
I'm having the same problem.
I call "gsresizestop" to refresh my charts to the new item-size but the item has the width and height from the resize-action of the user and not the actual one on the grid. **I think this is a bug**, since the gsresizestop should be called after the item has snapped to the grid.
A temporary solution could be setting a timeout and calculate the new width and height afterwards using jQuery, but this slows the application down quite a bit so I don't really want to implement this.

It seems like a fix was implemented in version 0.2.5-dev but never made it to the following versions (see issue #159 for reference). I've also tried using version 1.0.0-dev but it seems like there's no solution to this problem either so far.

**Comment by crazyfx1** [comment]
It depends on what you try to measure: The actual height in pixel of the height in cellHeight units.

As far as i can see the fix only contains the correct "height in cellHeight".

So basically in the gsresizestop function:
* The "height in pixel" (e.g. if you get the height of `.grid-stack-item` with jQuery) is definitely wrong. You can't rely on that.
* The "height in cellHeight" stored in data-gs-height is correct. So you can calculate the actual height if you multiplicate the value of the data-gs-height with your configured cellHeight + margins. This doesnt work for cellHeight=auto though.

The same goes for the width, but I think you are out of luck calculating there, because you might not know the width of 1 cell.

The fix would require to delay the gsresizestop event handler until the animation is finished.

**Comment by ramblingsoliloquy** [comment]
Thanks, @crazyfx1, calculating via cellHeight works fine! One needs to additionally subtract 4px due to the box-shadow, though, so:
`((gridItemHeight * gridCellHeight) + ((gridItemHeight - 1) * gridVerticalMargin)) - 4`

For the width I use `clientWidth` without any problems.

**Comment by radiolips** [comment]
@candrewtemenoscom I'm going to close this because it sounds like @crazyfx1 's got your back. Feel free to reopen if you're having continued issues.

**Comment by crazyfx1** [comment]
@radiolips glad you're back ;) i don't know if there is an open issue which addresses the bug that the event is triggered before the jQuery-Element has actually animated to the final size. This bug should be fixed nonetheless.

**Comment by radiolips** [comment]
I misunderstood. I could have sworn `gsresizestop` fixed the issue, but I must be mistaken. I'll take a look.

**Comment by adumesny** [comment]
refer #757

**Comment by adumesny** [comment]
fixed in 2.0 when events went native. resiszestop and dragstop are now called after the animation is done (final sizing)
