### ISSUE TITLE
How to save /load contents of widgets?

### ISSUE THREAD

**Issue by acbrandao** [gridstack/gridstack.js#855]
## Subject of the issue
What's the process to save and load the contents (hmtl) of the widgets, in the serialization example:
this.serializedData = [
			{x: 0, y: 0, width: 2, height: 2},
			{x: 3, y: 1, width: 1, height: 2},
			{x: 4, y: 1, width: 1, height: 1},
			{x: 2, y: 3, width: 3, height: 1},
			{x: 1, y: 4, width: 1, height: 1},
			{x: 1, y: 3, width: 1, height: 1},
			{x: 2, y: 4, width: 1, height: 1},
			{x: 2, y: 5, width: 1, height: 1}
		];

I don't see the  option /ability to retain that contents of the widget.

## Your environment
*latest  version of gridstack.js
* which browser Chrome latest version

**Comment by radiolips** [comment]
@acbrandao This is something that you'll need to do on your own. There are some closed out tickets that may have some explanation. In the serialized example, you can also loop over the widgets and store the HTML to a database or local storage - or you could store meta information about that HTML so that you can reconstruct it later.
