### ISSUE TITLE
Tiles in stacked mode can not be resized until switched to grid mode and back again

### ISSUE THREAD

**Issue by cursor-cko** [gridstack/gridstack.js#889]
## Subject of the issue
If starting in stacked mode, no tile can be resized. Even calling Grid.instance.enableResize(true); does not  help. After resizing the browser window or containing frame, the grid turns into grid mode. Shrinking the width back again, it turns into grid mode - and now, tiles are resizable as expected. But calling  Grid.instance.enableResize(true); makes them unresizable again.

## Your environment
Latest version of gridstack, every browser. See here in this gif:
![gridstackresizebug](https://user-images.githubusercontent.com/32901541/40178982-54d231da-59e3-11e8-8eb9-37d6938b6137.gif)

## Steps to reproduce
You can reproduce this issue on the homepage itself: http://gridstackjs.com/

## Expected behaviour
If resizable is set to true, even in stacked mode it should be resizable without requiring of turning into grid mode before.

**Comment by radiolips** [comment]
Thanks. I was able to replicate. We'll take a look.

**Comment by radiolips** [comment]
This has since been fixed. gridstackjs.com is using version 0.2.7 of gridstack - we're up to 0.4.0 now. Unfortunately, you'll find that you won't be able to resize in one column mode, so though the experience will now be consistent (resizing big/small won't be different if you start small), I don't think you'll find yourself very satisfied. I am planning on updating the responsive mode in the future, which will resolve your other issue.
