### ISSUE TITLE
URGENT - collisions are not handled properly in v3.+ 

### ISSUE THREAD

**Issue by artknight** [gridstack/gridstack.js#913]
I have tried upgrading my site's grid. The grid items are not handled correctly b/c they are allowed to occupy the same space. Attaching a screenshot.

<img width="874" alt="screen shot 2018-06-27 at 12 47 19 pm" src="https://user-images.githubusercontent.com/157762/41987894-956ff156-7a08-11e8-827e-baa2b6a107ed.png">

**Comment by artknight** [comment]
@radiolips I am wondering if it has to do with lodash 3. I am seeing in the docs that version 0.4 needs lodash 4+. Other than that, i simply downloaded the 0.4 release and ran the demo files.

**Comment by radiolips** [comment]
Ah, that definitely could be the problem. Could you try updating lodash, just as a test, and let me know how that goes?

**Comment by artknight** [comment]
Yes, upgrading to lodash 4.17 solves the issue! Unfortunately I can't upgrade my project to lodash v4 just yet. Do you think you could make igridstack 0.4 work with lodash 3?

( I am good on jquery, its upgraded to 3.1 )

**Comment by radiolips** [comment]
There's a very small change that could be done to make lodash 3 work. I was trying to avoid a patch release if people didn't need it, and you're the first person that has had a problem. We have a couple of options: I could tag a new release and just include that (I believe there are a couple more bug fixes that could go in there). It could wait until jQuery and lodash are removed (currently just working through jQueryUI resize, but drag-and-drop has already been complete). I could make the change in the `develop` branch, and you could point to that. I can open a new branch. Finally, I can inform you of the change needed to make lodash 3 work again.

I'd like to avoid a release because others haven't logged issue, but many of those other options would work okay. What do you think?

**Comment by artknight** [comment]
Yeah, not worth the hassle.. for sure. If you could just let me know what to change to make lodash 3 work, that would be fantastic. I think that would require the least amount of effort. Thanks :)

**Comment by radiolips** [comment]
Try changing this:
```
        sort: function(nodes, dir, width) {
             width = width || _.chain(nodes).map(function(node) { return node.x + node.width; }).max().value();
             dir = dir != -1 ? 1 : -1;
            return _.sortBy(nodes, [function(n) { return dir * (n.x + n.y * width); }]);
         },
```
to this:
```
        sort: function(nodes, dir, width) {
             width = width || _.chain(nodes).map(function(node) { return node.x + node.width; }).max().value();
             dir = dir != -1 ? 1 : -1;
            return _.sortBy(nodes, function(n) { return dir * (n.x + n.y * width); });
         },
```

**Comment by artknight** [comment]
My friend, you are da man!!!!!

**Comment by natalan** [comment]
Unfortunately, this means Gridstack 0.4 is not compatible with Underscore instead Lodash

**Comment by natalan** [comment]
I don't think this issue should be closed. There is a legit compatibility problem with the Gridstack v0.4 and the latest Underscore v1.9.1. @radiolips we should either remove this from README:
> Note: You can still use underscore.js (>= 1.7.0) instead of lodash.js

Or make `sort` backwards compatible.

**Comment by artknight** [comment]
I will let @radiolips make the call on this one. I am not sure if underscore.js should even be supported at this point. It hasn't had a release in forever.

**Comment by rsmarsh** [comment]
Thanks for this, turns out this was the cause of my issue too.
Dynamically added widgets would ignore all pre-existing widgets, and only move out of the way for widgets created after their own creation. 
Upgrading lodash from 3.x to 4.17.11 fixed this.
