### ISSUE TITLE
Refresh all widget properties when dropping it into other grids

### ISSUE THREAD

**Issue by danirueda** [gridstack/gridstack.js#924]
When you drop a widget from a grid to other Gridstack only sets the basic properties: `data-gs-x, data-gs-y, data-gs-width and data-gs-height`. But if the widget has other properties like `data-gs-min-height` or `data-gs-locked` these properties aren't cloned.

It would be useful to have a funcion called refreshWidget or similar for refreshing all the properties.

I've forked this repository and do this task myself, but I'm not sure if my code is correct for the authors. I can do a pull request.

**Comment by Hedva** [comment]
Always do a pull request if YOU think it's good enough, if it works and if it is an improvement.

If THEY think it doesn't fit in their code, they should add comments at your lines of code of your pull requests, for you to improve it. At that moment it's their responsibility to explain why your code isn't accepted (when that's the case), because only then it can be truly improved for a new pull request.

The worst thing that can happen; they don't accept the pull request.
Any other case; everyone can benefit from your piece of code.

**Comment by radiolips** [comment]
Totally! If I have some time soon, I'll try to put this in. @danirueda if you've still got your code, throw a PR our way! We'd love to merge your stuff in for this very valid use case.

**Comment by adumesny** [comment]
all data-gs- props are there (see updated two.html), but the resize/move feedback isn't totally in sync. Will file separate issue.
