### ISSUE TITLE
Automatic item height based on content

### ISSUE THREAD

**Issue by Guite** [gridstack/gridstack.js#936]
## Subject of the issue
I would like to determine the height of the items automatically instead of explicitly assigning a height argument. So the more height is required by the content of an item the more height it should get. Of course this means that also the `top` value can not be set to fixed values anymore. So probably this can not be done using the current absolute positioning of items.

Is this behaviour possible or how could it be done programmatically or by overriding css definitions?

## Your environment
* version of gridstack.js: 1.0.0-dev
* which browser and its version: all

**Comment by Skarnivorous** [comment]
As a work-around idea - perhaps you could just read the height of your content on insert (e.g. boundingClientRect) and then set the tile/grid item height accordingly?

**Comment by Guite** [comment]
This would be a foundation possibly. But there is more functionality required, at least a resize handler updating all heights and top positions.

**Comment by agenceKanvas** [comment]
Hi ! Any update on that ? thanks !

**Comment by radiolips** [comment]
Hey there! This is certainly possible. There's a closed out ticket which describes how, or one of the blog posts from my site (dylandreams.com - I think it might be the chart demo?) shows how to do it. It's actually not too much code to do it. At least for the time being, this is going to remain as an add-on with JS rather than being part of the core library. Good luck!
