### ISSUE TITLE
Grid stack become too slow when rending multiple widgets that have too much data. 

### ISSUE THREAD

**Issue by kashifasif** [gridstack/gridstack.js#971]
## Slow Grid Stack on Resizing and Moving 

grid stack is too slow on resizing and moving. my widgets have too much data and widgets are around about 15 on single page and i am using angularjs. please help me to resolve this issue. 

## Your environment
Version 0.4.0

## Expected behaviour
It should be fast on moving, resizing when i render from database.

**Comment by radiolips** [comment]
Hey @kashifasif. How much is in the DOM for these widgets? If you only have 15 widgets, it should be very fast.

**Comment by kashifasif** [comment]
Actually, I'm creating a BI tool like Power BI. I have different types of CanvasJS Charts + Tables + Google Map. and each charts is rendered by 4 Million record. and google map have almost 4000 Marker. each of widgets is coming from database.

**Comment by radiolips** [comment]
I'm not sure if this is fixable with gridstack in its current state. Maybe if changes were made to the shadow DOM, we might be able to speed it up, but because all of the changes are made to the live browser, the browser is rerendering everything. It's also presumably holding a lot in memory if you've got 15 * 4 million data points.

**Comment by radiolips** [comment]
I'm going to close this, because I don't think that there's any way to make this work without cutting down the number of data points. Rendering and rerendering is done by the browser, so while I agree that it should be fast, it also depends on how CanvasJS and the browser are doing the actual rendering.
