### ISSUE TITLE
Dragging widget into parent grid and nested child grid

### ISSUE THREAD

**Issue by ygalanter** [gridstack/gridstack.js#992]
I am trying to create this behavior and not sure whether Gridstack supports it or not. I have 3 grids: Grid1, Grid2, and Grid3.  Grid1 is a standalone grid and Grid3 is nested inside Grid2. I need to be able to drag widgets from Grid1 both into Grid2 (outer grid) and into Grid3 (nested grid). Following samples I was able to drag widgets between 2 top level grids and create a nested grid, but not combining these 2 together. If this is supported - any pointers are appreciated.

**Comment by Altraya** [comment]
I think you can take a look at this  #issue133. I think you need to play with the property "AcceptWidget" and css selector to achieve this.

**Comment by adumesny** [comment]
#1105 I just checked in will get you almost there - I updated nested.html to show drag&drop between 2 nested grids, but dragging a regular item into another nested one has tons of issues - it wants to push the out out first, then can drop into it - causing issues.  You can un-comment some settings to try.

Not an easy fix

**Comment by adumesny** [comment]
Robert de Wilde  in https://gridstackjs.com/demo/nested.html 

1. do you expect "regular item" (green) to move "nested 1" out of the way and also being able to be dropped it inside (becoming a pink item) ? if so we can't have both without an explicit Alt key press or something... which is somewhat hidden, but I don't think we can differentiate using just gesture.

2. dragging pink item "0" to parent yellow grid doesn't need special key (gesture explicit of dragging out, then will be be parented y yellow and push items, unless Alt key... BUT that doesn't work work moving pink between subgrids as it would leave and go to parent first). this is why this is tricky...

3. can "regular item" be turned into a nested grid (drag another item into it, with Alt key) and would you need to say ahead of time what items can become nested grid and which ones cannot ? see 4 

4. in the demo nested 1 & 2 have 6 columns layout (parent 12) - if we automatically convert any item into a grid, what column count would we use (set it per item config ?)

5. if I drag item0 over item1 with Alt key to drop into, do I convert item1 into subgrid of how many columns ? since item0 is same size (or could be bigger) it would take entire item1 columns - not clear what's expected here.

as you can see this is not easy to even design...

**Comment by RdeWilde** [comment]
Thanks @adumesny for setting an outline. I have limited experience ofcourse, you are the expert here, but here's my thought:

1. 
- Using a key is fine with me. 
- Or you have to divide items into different drop targets. 33% left is insert left, 33% right is insert right, other 34% is nest inside.
- Or you can have an icon inside the div to start dragging for nesting. Stripo has such labels in their editor
- Or show a context menu/popup on drop about what action to take

2. I don't get it, but i do understand it is not easy. Maybe check how other ui's handle this?

3. For my use case, I have a special type, so I can mark them as subgrids ahead of time. But if you can make it more generic, that would probably help other people a lot. But it's fine with me for now to keep scope small and only be able to drag into existing (sub)grids.

4. Same number of columns as before, with max of grid column size. I think you can't really convert it, converting 6/12 to */5 would require rounding. I would just keep it as is.

5. As said in 3) I'm fine with this being out of scope for now.
If you WOULD implement it, it depends on how/where the subgrid is being created, and maybe parameterize that. But I can undertand if you can't pull that off right now.

**Comment by adumesny** [comment]
@RdeWilde  comments:

1.
| Or you have to divide items into different drop targets. 33% left is insert left, 33% right is insert right, other 34% is nest inside.
wouldn't work as you drag over the first 1/3rd, the item would be pushed out of the way and you couldn't get to the mid point to insert nested instead (would be weird to bring item underneath again if you continue moving over nothing to insert)

| Or you can have an icon inside the div to start dragging for nesting. Stripo has such labels in their editor
as a lib I can't insert any affordances (I don't even enforce the type of DOM element just added classes) BUT you sure could and switch mode (insert vs move) for them. I think I will add that as a mode and have Alt key by default switch mode, but you could add UI to control which mode you're in.

| Or show a context menu/popup on drop about what action to take
again, lib can't have UI and you can't do after the fact as the feedback would be move or insert but not both...

3. & 4. I think I will require items that can be subgrid to be set ahead of time because I need to know the column count/cellHeight, which may need to be different from the parent.

**Comment by RdeWilde** [comment]
Sounds good to me @adumesny

**Comment by arclogos132** [comment]
> 1. do you expect "regular item" (green) to move "nested 1" out of the way and also being able to be dropped it inside (becoming a pink item) ? if so we can't have both without an explicit Alt key press or something... which is somewhat hidden, but I don't think we can differentiate using just gesture.
No Alt key, no moving "nested 1" out of the way. I just need dropping in (which works now)

> 2. dragging pink item "0" to parent yellow grid doesn't need special key (gesture explicit of dragging out, then will be be parented by yellow and push items, unless Alt key... BUT that doesn't work work moving pink between subgrids as it would leave and go to parent first). this is why this is tricky...
I need to drag an item out of a subgrid into a parent grid, and vice-versa.

> 3. can "regular item" be turned into a nested grid (drag another item into it, with Alt key) and would you need to say ahead of time what items can become nested grid and which ones cannot ? see 4
It would be an awesome feature, but I personally don't need this right now, considering how difficult it would be to implement.

> 4. in the demo nested 1 & 2 have 6 columns layout (parent 12) - if we automatically convert any item into a grid, what column count would we use (set it per item config ?)
No need to convert an item into a nested grid for now.

> 5. if I drag item0 over item1 with Alt key to drop into, do I convert item1 into subgrid of how many columns ? since item0 is same size (or could be bigger) it would take entire item1 columns - not clear what's expected here.
Same as my answer to Q4.

@adumesny

**Comment by arclogos132** [comment]
https://github.com/gridstack/gridstack.js/blob/master/demo/nested.html#L50
> acceptWidgets: '.grid-stack-item.sub', // only pink sub items can be inserted, otherwise grid-items causes all sort of issues

**Comment by arclogos132** [comment]
https://user-images.githubusercontent.com/54137057/147026405-ed76c371-e21e-4070-ac09-924cf020255f.mov

Video of not being able to put an item back into a sub grid, while dragging it out of the sub grid into its parent grid works fine.

**Comment by adumesny** [comment]
got most of it working for upcoming release...

https://user-images.githubusercontent.com/3496166/147439184-9898199c-8664-475e-b319-b12983c5ea1a.mp4

**Comment by arclogos132** [comment]
That looks beautiful

**Comment by adumesny** [comment]
some issue remain (nested within nested break things) - re-opening

https://user-images.githubusercontent.com/3496166/147688146-7d307caa-0cc4-4a6c-85ea-57b6f7ff3299.mp4

**Comment by adumesny** [comment]
fixed 
https://user-images.githubusercontent.com/3496166/147726502-ea6354b7-bd1e-4b5c-b19a-46bb59a0b7cf.mp4

**Comment by adumesny** [comment]
got the nested drag (which was disabled) fixed as part of #1009 (changelist #2052) for v7

https://user-images.githubusercontent.com/3496166/192298440-e7af6f41-2324-4e8c-9f5a-bda3ef382d42.mp4

but the mouseenter event is used today to add items to a grid, when it should really be 50% coverage like between items - so you can't really push vs nest between sub-grid (depending on where your cursor is) - that will have to be future tweaks
