### ISSUE TITLE
Cannot Load elements as Maximum call stack size error displayed.

### ISSUE THREAD

**Issue by nsgalib** [gridstack/gridstack.js#994]
## Subject of the issue
Trying to create a dynamic dashboard with drag/drop and resize functionality. I want to add ASP server controls to 'grid-stack-item-content' and update them through Ajax after every 10 seconds. 

## Your environment
* version of gridstack.js 0.4.0
* Google Chrome Version 74.0.3729.108 (Official Build) (64-bit)

## Steps to reproduce
https://jsfiddle.net/kLeu7y0h/

## Expected behaviour
Should Load Elements through JSON string retrieved from database.

## Actual behaviour
Cannot load elements as maximum call stack size error displayed.

**Comment by adumesny** [comment]
@nsgalib I tried your code (and see the inf loop error against 0.4.0) against the latest current code 0.5.1-dev and the inf loop error is GONE, but the grid doesn't load up so it's something you'll need to debug to see if it's your code at this point. check out this sample code that works
https://gridstackjs.com/demo/serialization.html (source on github under demo)

I attached the file here for reference.
[test.zip](https://github.com/gridstack/gridstack.js/files/3825396/test.zip)

closing for now, please re-open if the issue persist on the lib side.

**Comment by roldeguz** [comment]
@nsgalib @adumesny The reason its not loading is because the "id" is not being passed in the addWidget function call and then in the saveGrid function, node.id is being referenced and at that point the value is undefined. It's just weird to use the actual div element as the id, moni1 instead of "moni1".

If you swap `id: node.id` with `id: el[0]`, it will work. 

About the maximum call stack size, if you pass the autopos arg and set it to false in addWidget(), it will work in 0.4.0.
